(define (domain foodprepworld)
    (:predicates
        (vegetable ?x)
        (sink ?x)
        (is_clean ?x)
        (surface ?x)
        (in ?x ?y)
        (on ?x ?y)
        (empty ?x)
        (holding ?x ?y)
        (hand ?x)
        (bowl ?x)
        (cuttingboard ?x)
        (knife ?x)
        (is_cut ?x)
        (crunchy ?x)
        (leafy ?x)
        (mixer ?x)
        (salad_ready_in ?x)
    )

    (:action wash
        :parameters (?v ?s)
        :precondition (and (vegetable ?v) (sink ?s) (in ?v ?s))
        :effect (is_clean ?v)
    )

    (:action pickup
        :parameters (?x ?y ?h)
        :precondition (and 
                        (empty ?h)
                        (hand ?h)
                        (or (on ?x ?y) (in ?x ?y))
                    )
        :effect (and 
                    (not (empty ?h)) 
                    (not (on ?x ?y)) 
                    (not (in ?x ?y)) 
                    (holding ?x ?h)
                )
    )

    (:action put_in
        :parameters (?x ?y ?h)
        :precondition (and (holding ?x ?h) (or (sink ?y) (bowl ?y)) (hand ?h))
        :effect (and (empty ?h) (in ?x ?y) (not (holding ?x ?h)))
    )

    (:action put_on
        :parameters (?x ?y ?h)
        :precondition (and (holding ?x ?h) (surface ?y) (hand ?h))
        :effect (and (empty ?h) (not (holding ?x ?h)) (on ?x ?y))
    )

    (:action chop
        :parameters (?x ?k ?h ?b)
        :precondition (and 
                (vegetable ?x)
                (hand ?h)
                (knife ?k)
                (cuttingboard ?b)
                (on ?x ?b)
                (holding ?k ?h)
                (is_clean ?x))
        :effect (is_cut ?x)
    )

    (:action mix_salad
        :parameters (?a ?b ?c ?d ?e ?f ?g ?h)
        :precondition (and
                (vegetable ?a)
                (leafy ?a)
                (vegetable ?b)
                (vegetable ?c)
                (vegetable ?d)
                (crunchy ?e)
                (bowl ?f)
                (mixer ?g)
                (is_clean ?a)
                (is_clean ?b)
                (is_clean ?c)
                (is_clean ?d)
                (is_cut ?a)
                (is_cut ?b)
                (is_cut ?c)
                (is_cut ?d)
                (in ?a ?f)
                (in ?b ?f)
                (in ?c ?f)
                (in ?d ?f)
                (in ?e ?f)
                (holding ?g ?h)
                (not (= ?a ?b))
                (not (= ?a ?c))
                (not (= ?a ?d))
                (not (= ?b ?c))
                (not (= ?b ?d))
                (not (= ?c ?d))
        )
        :effect (salad_ready_in ?f)
    )
)